root = "."
tmp_dir = "tmp"

[build]
  cmd = "go mod tidy && go build -o tmp/main cmd/api/main.go"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "tmp", "node_modules"]

[log]
  level = "debug"
