version: '3.8'

services:
  cloud-spend-air:
    image: cloud-spend
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp
    command: ["air", "-c", ".air.toml"]
    restart: always
