services:
  db:
    image: postgres
    container_name: cloudspend_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: joshua
      POSTGRES_DB: cloudspend
    volumes:
      - /home/joshua/projects/postgres-pgadmin/pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: cloudspend_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: joshuasajeevnv@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8090:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  app:
    build: .
    container_name: cloudspend_app
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: joshua
      DB_NAME: cloudspend
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["air", "-c", ".air.toml"]
    restart: unless-stopped
